examples/sample/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :pings, only: %i[index show]

  resources :users, only: %i[index show new create]

  get '/login', to: 'sessions#index'
  post '/login', to: 'sessions#login'
  post '/logout', to: 'sessions#logout'

  get '/mypage', to: 'mypage#index'
end

examples/sample/app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

examples/sample/app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  validates :name, presence: true
end

examples/sample/app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include ActionHandler::Controller

  helper_method :current_user

  def current_user
    unless @current_user_set
      user_id = session[:user_id]
      @current_user = User.find_by(id: user_id) if user_id
      @current_user_set = true
    end
    @current_user
  end
end

examples/sample/app/controllers/mypage_controller.rb
# frozen_string_literal: true

class MypageHandler
  include ActionHandler::Equip

  as_controller do
    before_action do
      redirect_to login_path if current_user.nil?
    end
  end

  args SessionArgs.instance

  arg(:theme) do |ctrl|
    ctrl.params[:theme]
  end

  def initialize(greeter: MypageService.new)
    @greeter = greeter
  end

  def index(current_user, theme)
    render locals: {
      user: current_user,
      welcome: @greeter.welcome(current_user, theme),
    }
  end
end

class MypageController < ApplicationController
  use_handler { MypageHandler.new }
end

examples/sample/app/controllers/pings_controller.rb
# frozen_string_literal: true

class PingsHandler
  include ActionHandler::Equip

  def index
    { locals: { pong: :pong_from_handler } }
  end

  def show(params, format)
    if format == :json
      render json: {
        id: params[:id],
        pong: "pong by #{params[:id]}",
      }
    else
      render plain: 'Pong!'
    end
  end
end

class PingsController < ApplicationController
  use_handler { PingsHandler.new }
end

examples/sample/app/controllers/sessions_controller.rb
# frozen_string_literal: true

# WARNING: This is just a sample of action handler.
class SessionsHandler
  include ActionHandler::Equip

  args SessionArgs.instance

  def index(current_user)
    redirect_to urls.mypage_path if current_user
  end

  def login(params:, session:, reset_session:)
    user = User.find_by(name: params[:name])
    return redirect_to urls.login_path, alert: "#{params[:name]} does not exist" if user.nil?

    reset_session.call
    session[:user_id] = user.id
    redirect_to urls.mypage_path
  end

  def logout(session)
    session.delete(:user_id)
    redirect_to urls.login_path
  end
end

class SessionsController < ApplicationController
  use_handler { SessionsHandler.new }
end

examples/sample/app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersHandler
  include ActionHandler::Equip

  args_params user: %i[name]

  def index
    users = User.all
    render locals: { users: users }
  end

  def show(params)
    user = User.find(params[:id])
    render locals: { user: user }
  end

  def new
    render locals: { user: User.new }
  end

  def create(user)
    user = User.create!(user)
    redirect_to urls.user_path(user.id)
  end
end

class UsersController < ApplicationController
  use_handler { UsersHandler.new }
end

examples/sample/app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

examples/sample/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>

  <body>
    <header>
      <% if current_user %>
        <%= link_to('Mypage', mypage_path) %>
      <% else %>
        <%= link_to('Log in', login_path) %>
      <% end %>

      <%= link_to('users', users_path) %>
    </header>
    <hr>

    <% if flash[:alert] %>
      <p><%= flash[:alert] %></p>
    <% end %>

    <%= yield %>
  </body>
</html>

examples/sample/app/views/mypage/index.html.erb
<h1><%= welcome %></h1>

Your ID is <%= user.id %>

<%= form_with(url: logout_path) do %>
  <button type="submit">Log out</button>
<% end %>

examples/sample/app/views/pings/index.html.erb
<h1>Pings#index</h1>
<p>
  Response: <%= pong %>
</p>

examples/sample/app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

examples/sample/app/views/users/index.html.erb
<h1>Users</h1>

<ul>
  <% users.each do |user| %>
    <li>
      <%= link_to(user.name, user_path(user)) %>
    </li>
  <% end %>
</ul>

<%= link_to("New user", new_user_path) %>

examples/sample/app/views/users/new.html.erb
<h1>New user</h1>
<%= form_with(model: user) do |f| %>
  <%= f.text_field(:name) %>
  <button type="submit">Register</button>
<% end %>

examples/sample/app/views/users/show.html.erb
<h1>User <%= user.name %></h1>
ID: <%= user.id %>